### ISSUE TITLE
Error when using label/name in a device driver

### ISSUE THREAD

**Issue by cmorse** [biocomp/hubitat_ci#6]
I am running into an error when I try to use label or name in a device driver:

```
In [initialization] settings were read that are not registered inputs: [label, name]. These are registered inputs: [logEnable, txtEnable]. This is not allowed in strict mode (add Flags.AllowReadingNonInputSettings to allow this). Expression: readSettingsThatAreNotInputs. Values: readSettingsThatAreNotInputs = [label, name]
java.lang.AssertionError: In [initialization] settings were read that are not registered inputs: [label, name]. These are registered inputs: [logEnable, txtEnable]. This is not allowed in strict mode (add Flags.AllowReadingNonInputSettings to allow this). Expression: readSettingsThatAreNotInputs. Values: readSettingsThatAreNotInputs = [label, name]
    at me.biocomp.hubitat_ci.validation.SettingsContainer.validateAfterPreferences(SettingsContainer.groovy:43)
    at me.biocomp.hubitat_ci.device.HubitatDeviceScript.hubitatciValidateAfterMethodCall(HubitatDeviceScript.groovy:85)
    at TestMyDevice.log function test(my-device-test.groovy:31)
```

I suspect this might just be a feature that's not implemented yet. I can probably take care of implementing it if you point me in the right direction.

**Comment by cmorse** [comment]
To answer your question on the hubitat community forum:

As far as I can tell `name` and `label` are standard properties of the driver: See [getName docs] (https://docs.smartthings.com/en/latest/ref-docs/device-ref.html#getname) and [getLabel docs](https://docs.smartthings.com/en/latest/ref-docs/device-ref.html#getlabel)

**Comment by biocomp** [comment]
I see. But there were no such methods for Hubitat last time I reflected its APIs. However, it was a while ago, maybe things have changed. Does it actually work in Hubitat? Like not returning `null`?

I'll see if the methods are now present later.

**Comment by cmorse** [comment]
Yeah, they both definitely work. `getLabel()` returns null by default, unless a label was manually set by the user or the label was set when the device was created. As far as I know, `getName()` always returns something.

**Comment by biocomp** [comment]
There are no methods `getName()` and `getLabel()` callable from device driver. I've checked updated existing method signatures on the class.

And if I use `name` and `label` properties, they always return `null` even if I set devices' label. I have just checked on my Hubitat.

Have you tried those in your driver and see valid output?

If they are not there, and they are widely used everywhere, we can probably still add them. But from the several drivers I could find and test in github, none were using `name` or `label`.

This is my device's output:
```
Failed to call getLabel(): groovy.lang.MissingMethodException: No signature of method: user_driver_me_biocomp_Logging_switch_206.getLabel() is applicable for argument types: () values: []
Possible solutions: getClass(), getAt(java.lang.String)
info My lavel is label = null
error Failed to call getName(): groovy.lang.MissingMethodException: No signature of method: user_driver_me_biocomp_Logging_switch_206.getName() is applicable for argument types: () values: []
Possible solutions: getAt(java.lang.String), getClass()
info My name is name = null
```

**Comment by cmorse** [comment]
From looking at my code again, it looks like I misspoke originally. I've been calling `device.label` and `device.name`, not `label` and `name`. Sorry about the confusion.

The `getName` and `getLabel` functions do show up in the [DeviceWrapper](https://github.com/biocomp/hubitat_ci/blob/f08f8b63cae8dc0d33d1cb307582f0923a8f99d1/src/main/groovy/me/biocomp/hubitat_ci/api/common_api/DeviceWrapper.groovy) (Lines 141 and 161), and in [ChildDeviceWrapper](https://github.com/biocomp/hubitat_ci/blob/f08f8b63cae8dc0d33d1cb307582f0923a8f99d1/src/main/groovy/me/biocomp/hubitat_ci/api/common_api/ChildDeviceWrapper.groovy) (Lines 34 and 36).

I have used `device.name` and `device.label` in my device drivers, and it definitely works. I found an example of a publicly available driver using `device.label` in a log statement [here](https://github.com/DaveGut/Hubitat-TP-Link-Integration/blob/master/DeviceDrivers/TP-LinkMulti-Plug(Hubitat).groovy#L240-L246). Since I use that specific driver myself, here's an example of the log output from it:

```
dev:11 2019-09-10 00:13:36.202 warn Outlet - Garage - Door Opener 4.3.01 Attempt 1 to recover communications
dev:11 2019-09-10 00:13:36.097 warn Error occured with UDP message: SocketTimeoutException: Receive timed out
```

In this case, the device label is set to 'Outlet - Garage - Door Opener' in the hubitat UI.

**Comment by biocomp** [comment]
Ah, ok. Now this makes more sense :). I'll try that out and see why it's not working. So you're saying that `device.label` and `device.name` is triggering that error about `name` and `device` not being inputs?

**Comment by cmorse** [comment]
I'll make sure of what the original error was when I get home. I suspect I made some changes to things while trying to debug, and that's what made me thing that `name` and `label` existed.

**Comment by cmorse** [comment]
Here's the original error I was getting. 

```
Cannot get property 'label' on null object
java.lang.NullPointerException: Cannot get property 'label' on null object
	at my-device-websocket.myLog_original(my-device.groovy:125)
	at TestMyDevice.log function test(my-device-test.groovy:33)
```

It looks like `device` is null.

**Comment by biocomp** [comment]
Ah, well, this is easy. This is by design. You're essentially calling `getDevice().label`. Your script class has default implementation of `getDevice()`, which returns `null`. What you need to do is to mock `getDevice()` method to return a non-null object. 

You can see me doing this in this example: https://github.com/biocomp/hubitat_ci_example/blob/master/minimal/src/test.groovy for `getLog()`.

You'll need to use `Mock(DeviceWrapper)` instead, and in that mock, you can implement `getName()` and `getLabel()` to return something meaningful:

Note: I did not compile the code below, but I hope you get the idea.
```groovy
def device = Mock(DeviceWrapper){ 
   _*getName() >> "My device" 
   _*getLabel() >> "My device label" 
}

DeviceExecutor api = Mock{ _*getDevice() >> device }
def script = sandbox.run(api: api)
```

**Comment by biocomp** [comment]
Same goes for any other Hubitat apis you're calling (besides initialization part of the script, which is implemented and is used in validation). They are not implemented, and you'll have to stub/mock them out.
